const types = {
  FETCH_ESTABLISHMENT: "@establishment/FETCH_ESTABLISHMENT",
  UPDATE_ESTABLISHMENT: "@establishment/UPDATE_ESTABLISHMENT",
  SAVE_ESTABLISHMENT: "@establishment/SAVE_ESTABLISHMENT",
  SET_ESTABLISHMENT_LOADING: "@establishment/SET_ESTABLISHMENT_LOADING",
  SET_ESTABLISHMENT_SAVING: "@establishment/SET_ESTABLISHMENT_SAVING",
  RESET_ESTABLISHMENT: "@establishment/RESET_ESTABLISHMENT",
};

export default types;
